# Generated by Django 5.1.7 on 2025-05-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('residence_type', models.CharField(max_length=50)),
                ('month_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_loan', models.BooleanField()),
                ('marital_status', models.CharField(max_length=10)),
                ('dependency', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
